# Generated by Django 5.1.7 on 2025-04-02 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_reader_readingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingrecord',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.book'),
        ),
        migrations.AddField(
            model_name='readingrecord',
            name='reader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.reader'),
        ),
    ]
