# Generated by Django 5.1.7 on 2025-04-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_readingrecord_book_readingrecord_reader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingrecord',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='readingrecord',
            name='date_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='readingrecord',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='readingrecord',
            name='state',
            field=models.TextField(choices=[('A', 'Chci číst'), ('B', 'Právě čtu'), ('C', 'Přečteno'), ('D', 'Nechci číst')], max_length=1),
        ),
    ]
