# Generated by Django 5.1.7 on 2025-04-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_readingrecord_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingrecord',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='readingrecord',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='readingrecord',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
